apiVersion: v2
name: recurring-consumer
description: A Helm chart for Recurring Consumer Service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - consumer
  - recurring
  - kafka
  - dapr
maintainers:
  - name: Phase V Cloud-Native Deployment
