apiVersion: v2
name: audit-consumer
description: A Helm chart for Audit Consumer Service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - consumer
  - audit
  - kafka
  - dapr
maintainers:
  - name: Phase V Cloud-Native Deployment
